### ISSUE TITLE
AutoDock Types for DNA/RNA

### ISSUE THREAD

**Issue by adamhospital** [bioexcel/biobb_structure_checking#10]
Is it planned to add AutoDock Types for DNA/RNA? 

https://github.com/bioexcel/biobb_structure_checking/blob/579e241b7716f8add77f3ab245e6bb089c680422/biobb_structure_checking/dat/ADT_prm.json#L130

Thanks!

**Comment by jlgelpi** [comment]
Done in 4937434226f10c099a293925542f048f2037ea76
