### ISSUE TITLE
mutation with modeller just removes the target residue when it's on the first 2 positions

### ISSUE THREAD

**Issue by pgbarletta** [bioexcel/biobb_structure_checking#17]
Hi,

This works:
```
check_structure -i a.pdb -o b.pdb mutateside --mut B:Pro3Glu --rebuild
```
this also works:
```
check_structure -i a.pdb -o c.pdb mutateside --mut B:Ala2Glu
```
but this line just removes the second alanine:
```
check_structure -i a.pdb -o b.pdb mutateside --mut B:Ala2Glu --rebuild
```
And the same thing happens on the first position:
```
check_structure -i a.pdb -o b.pdb mutateside --mut B:Ala1Glu --rebuild
```
So, starting on position 3, everything works, but mutating in the first 2, fails.

I got lost during the debugging, but apparently the comment on [this](https://github.com/bioexcel/biobb_structure_checking/blob/aea94d230933ed275661457c508a451edf77f00d/biobb_structure_checking/structure_manager.py#L1450) line predicted this outcome.

The way `mutated_sequence_data` is built [here](https://github.com/bioexcel/biobb_structure_checking/blob/aea94d230933ed275661457c508a451edf77f00d/biobb_structure_checking/structure_manager.py#L1442-L1448) prevents `merge_structure()` from actually merging the fragments, since [this](https://github.com/bioexcel/biobb_structure_checking/blob/aea94d230933ed275661457c508a451edf77f00d/biobb_structure_checking/structure_manager.py#L1140) loop doesn't get to run.

Apparently the function in charge of getting the fragments [`read_structure()`](https://github.com/bioexcel/biobb_structure_checking/blob/aea94d230933ed275661457c508a451edf77f00d/biobb_structure_checking/sequence_manager.py#L155), doesn't build 2 separate fragments when the mutated residue is on either of the first 2 positions. So, `len(sequence_data.data[ch_id]['pdb'][mod_id]['frgs'])` is `1` (there's only 1 fragment)  and the aforementioned loop doesn't run. There may be some other issues as well beyond this loop not running, but that's as far as I went.

I do wonder though, why this is splitting is being done. Modeller does allow the user to select which residues to refine, so there shouldn't be any overhead for dealing with the whole structure, and one would be sure that modeller will try to avoid any clashes against the rest of the structure. This way, modeller doesn't get the whole picture and is unable to properly minimize its model.

Kind regards,

edit: oops, forgot to add the [input and output files](https://gist.github.com/pgbarletta/667f21acdc5d5a25a6534f0da80e2890) I collected.

**Comment by jlgelpi** [comment]
Thanks for the feedback. Indeed this is known bug. Mutations rebuild use the machinery of backbone breaks repair (that is what makes the debugging that problematic, I apologize).  Actually the whole model is build, but only the required regions are transferred to the structure. This prevents that distortions of the original structure introduced by Modeller in some ocasions. 
I any case it would be solved in a coming release, as the complete Modeller interface is being revised.

**Comment by pgbarletta** [comment]
Cool, good to know. Thanks.
